/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laberintoproyecto.vista;

import java.awt.event.ActionListener;
import java.awt.event.KeyListener;

/**
 *
 * @author Andrey
 */
public class GUILaberinto extends javax.swing.JFrame {

    /**
     * Creates new form GUIJuego
     */
    public GUILaberinto() {
        initComponents();
    }

    public PanelLaberinto getPanelLaberinto() {
        return panelLaberinto;
    }

    public void escuchar(ActionListener controlador) {
        btnLeave.addActionListener(controlador);
    }
    
    public void escucharTeclado (KeyListener controlador) {
        this.addKeyListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLeave = new javax.swing.JButton();
        panelLaberinto = new com.mycompany.laberintoproyecto.vista.PanelLaberinto();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLeave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnLeaveSmall.png"))); // NOI18N
        btnLeave.setActionCommand("leaveplay");
        btnLeave.setBorder(null);
        btnLeave.setBorderPainted(false);
        btnLeave.setContentAreaFilled(false);
        btnLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLeave.setFocusPainted(false);
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 180, 90));

        javax.swing.GroupLayout panelLaberintoLayout = new javax.swing.GroupLayout(panelLaberinto);
        panelLaberinto.setLayout(panelLaberintoLayout);
        panelLaberintoLayout.setHorizontalGroup(
            panelLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        panelLaberintoLayout.setVerticalGroup(
            panelLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(panelLaberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 934, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoJuego.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeave;
    private javax.swing.JLabel jLabel1;
    private com.mycompany.laberintoproyecto.vista.PanelLaberinto panelLaberinto;
    // End of variables declaration//GEN-END:variables
}
