/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laberintoproyecto.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author Andrey
 */
public class GUIPerdida extends javax.swing.JFrame {

    /**
     * Creates new form GUIPerdida
     */
    public GUIPerdida() {
        initComponents();
    }

    public void escuchar(ActionListener controlador) {
        btnRestart.addActionListener(controlador);
        btnLeave.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRestart = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRestart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnRestart.png"))); // NOI18N
        btnRestart.setActionCommand("play");
        btnRestart.setBorderPainted(false);
        btnRestart.setContentAreaFilled(false);
        btnRestart.setFocusPainted(false);
        getContentPane().add(btnRestart, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, -1, -1));

        btnLeave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnLeaveForCondition.png"))); // NOI18N
        btnLeave.setActionCommand("leaveplay");
        btnLeave.setBorderPainted(false);
        btnLeave.setContentAreaFilled(false);
        btnLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLeave.setFocusPainted(false);
        getContentPane().add(btnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoPerdio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnRestart;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
