/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.laberintoproyecto.vista;

import com.mycompany.laberintoproyecto.controlador.ControladorPrincipal;

/**
 *
 * @author Andrey
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
        setVisible(true);
    }

    public void escuchar(ControladorPrincipal controlador) {
        btnPlay.addActionListener(controlador);
        btnGuide.addActionListener(controlador);
        btnHistory.addActionListener(controlador);
        btnLeave.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlay = new javax.swing.JButton();
        btnGuide = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnPlay.png"))); // NOI18N
        btnPlay.setActionCommand("play");
        btnPlay.setBorder(null);
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.setFocusPainted(false);
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        btnGuide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnGuide.png"))); // NOI18N
        btnGuide.setActionCommand("guide");
        btnGuide.setBorder(null);
        btnGuide.setBorderPainted(false);
        btnGuide.setContentAreaFilled(false);
        btnGuide.setFocusPainted(false);
        btnGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuideActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnHistory.png"))); // NOI18N
        btnHistory.setActionCommand("history");
        btnHistory.setBorder(null);
        btnHistory.setBorderPainted(false);
        btnHistory.setContentAreaFilled(false);
        btnHistory.setFocusPainted(false);
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        btnLeave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnLeave.png"))); // NOI18N
        btnLeave.setActionCommand("leave");
        btnLeave.setBorder(null);
        btnLeave.setBorderPainted(false);
        btnLeave.setContentAreaFilled(false);
        btnLeave.setFocusPainted(false);
        getContentPane().add(btnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoMenu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuideActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuide;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
