/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.laberintoproyecto.vista;

import com.mycompany.laberintoproyecto.controlador.ControladorLaberinto;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Andrey
 */
public class PanelLaberinto extends javax.swing.JPanel {

    private ControladorLaberinto controlador;
    private ImageIcon fondo;

    /**
     * Creates new form PanelLaberinto
     */
    
    public PanelLaberinto() {
        initComponents();
        fondo = new ImageIcon("./src/main/resources/img/Laberinto.png");
    }
    

    public void setControlador(ControladorLaberinto controlador) {
        this.controlador = controlador;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        fondo.paintIcon(null, g, 0, 0);
        if (controlador != null) {
            controlador.dibujar(g);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
